/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.conferenceProgram;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgramFactory
 * @model kind="package"
 * @generated
 */
public interface ConferenceProgramPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "conferenceProgram";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/ConferenceProgram";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "conferenceProgram";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ConferenceProgramPackage eINSTANCE = org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramImpl <em>Conference Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getConferenceProgram()
   * @generated
   */
  int CONFERENCE_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFERENCE_PROGRAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFERENCE_PROGRAM__DATE = 1;

  /**
   * The feature id for the '<em><b>Researchtracks</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFERENCE_PROGRAM__RESEARCHTRACKS = 2;

  /**
   * The feature id for the '<em><b>Industrytracks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFERENCE_PROGRAM__INDUSTRYTRACKS = 3;

  /**
   * The feature id for the '<em><b>Demosandposterstrack</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFERENCE_PROGRAM__DEMOSANDPOSTERSTRACK = 4;

  /**
   * The feature id for the '<em><b>Panelstrack</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFERENCE_PROGRAM__PANELSTRACK = 5;

  /**
   * The feature id for the '<em><b>Social Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFERENCE_PROGRAM__SOCIAL_EVENTS = 6;

  /**
   * The feature id for the '<em><b>Keynotes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFERENCE_PROGRAM__KEYNOTES = 7;

  /**
   * The feature id for the '<em><b>Coffebreaks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFERENCE_PROGRAM__COFFEBREAKS = 8;

  /**
   * The feature id for the '<em><b>Lunches</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFERENCE_PROGRAM__LUNCHES = 9;

  /**
   * The number of structural features of the '<em>Conference Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFERENCE_PROGRAM_FEATURE_COUNT = 10;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.ResearchTrackImpl <em>Research Track</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ResearchTrackImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getResearchTrack()
   * @generated
   */
  int RESEARCH_TRACK = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESEARCH_TRACK__NAME = 0;

  /**
   * The feature id for the '<em><b>Researchsession</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESEARCH_TRACK__RESEARCHSESSION = 1;

  /**
   * The number of structural features of the '<em>Research Track</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESEARCH_TRACK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.IndustryTrackImpl <em>Industry Track</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.IndustryTrackImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getIndustryTrack()
   * @generated
   */
  int INDUSTRY_TRACK = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDUSTRY_TRACK__NAME = 0;

  /**
   * The feature id for the '<em><b>Indutrysession</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDUSTRY_TRACK__INDUTRYSESSION = 1;

  /**
   * The number of structural features of the '<em>Industry Track</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDUSTRY_TRACK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.DemosAndPosterTrackImpl <em>Demos And Poster Track</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.DemosAndPosterTrackImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getDemosAndPosterTrack()
   * @generated
   */
  int DEMOS_AND_POSTER_TRACK = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEMOS_AND_POSTER_TRACK__NAME = 0;

  /**
   * The feature id for the '<em><b>Demosession</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEMOS_AND_POSTER_TRACK__DEMOSESSION = 1;

  /**
   * The number of structural features of the '<em>Demos And Poster Track</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEMOS_AND_POSTER_TRACK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.PanelTrackImpl <em>Panel Track</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.PanelTrackImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getPanelTrack()
   * @generated
   */
  int PANEL_TRACK = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANEL_TRACK__NAME = 0;

  /**
   * The feature id for the '<em><b>Panelsession</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANEL_TRACK__PANELSESSION = 1;

  /**
   * The number of structural features of the '<em>Panel Track</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANEL_TRACK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.ResearchSessionImpl <em>Research Session</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ResearchSessionImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getResearchSession()
   * @generated
   */
  int RESEARCH_SESSION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESEARCH_SESSION__NAME = 0;

  /**
   * The feature id for the '<em><b>Researchpaper</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESEARCH_SESSION__RESEARCHPAPER = 1;

  /**
   * The feature id for the '<em><b>Location</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESEARCH_SESSION__LOCATION = 2;

  /**
   * The feature id for the '<em><b>Start Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESEARCH_SESSION__START_TIME = 3;

  /**
   * The feature id for the '<em><b>End Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESEARCH_SESSION__END_TIME = 4;

  /**
   * The number of structural features of the '<em>Research Session</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESEARCH_SESSION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.IndustrySessionImpl <em>Industry Session</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.IndustrySessionImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getIndustrySession()
   * @generated
   */
  int INDUSTRY_SESSION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDUSTRY_SESSION__NAME = 0;

  /**
   * The feature id for the '<em><b>Industrypaper</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDUSTRY_SESSION__INDUSTRYPAPER = 1;

  /**
   * The feature id for the '<em><b>Location</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDUSTRY_SESSION__LOCATION = 2;

  /**
   * The feature id for the '<em><b>Start Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDUSTRY_SESSION__START_TIME = 3;

  /**
   * The feature id for the '<em><b>End Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDUSTRY_SESSION__END_TIME = 4;

  /**
   * The number of structural features of the '<em>Industry Session</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDUSTRY_SESSION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.DemoSessionImpl <em>Demo Session</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.DemoSessionImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getDemoSession()
   * @generated
   */
  int DEMO_SESSION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEMO_SESSION__NAME = 0;

  /**
   * The feature id for the '<em><b>Demoandposter</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEMO_SESSION__DEMOANDPOSTER = 1;

  /**
   * The feature id for the '<em><b>Location</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEMO_SESSION__LOCATION = 2;

  /**
   * The feature id for the '<em><b>Start Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEMO_SESSION__START_TIME = 3;

  /**
   * The feature id for the '<em><b>End Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEMO_SESSION__END_TIME = 4;

  /**
   * The number of structural features of the '<em>Demo Session</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEMO_SESSION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.PanelSessionImpl <em>Panel Session</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.PanelSessionImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getPanelSession()
   * @generated
   */
  int PANEL_SESSION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANEL_SESSION__NAME = 0;

  /**
   * The feature id for the '<em><b>Panel</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANEL_SESSION__PANEL = 1;

  /**
   * The feature id for the '<em><b>Location</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANEL_SESSION__LOCATION = 2;

  /**
   * The feature id for the '<em><b>Start Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANEL_SESSION__START_TIME = 3;

  /**
   * The feature id for the '<em><b>End Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANEL_SESSION__END_TIME = 4;

  /**
   * The number of structural features of the '<em>Panel Session</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANEL_SESSION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.ResearchPaperImpl <em>Research Paper</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ResearchPaperImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getResearchPaper()
   * @generated
   */
  int RESEARCH_PAPER = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESEARCH_PAPER__NAME = 0;

  /**
   * The number of structural features of the '<em>Research Paper</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESEARCH_PAPER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.IndustryPaperImpl <em>Industry Paper</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.IndustryPaperImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getIndustryPaper()
   * @generated
   */
  int INDUSTRY_PAPER = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDUSTRY_PAPER__NAME = 0;

  /**
   * The number of structural features of the '<em>Industry Paper</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDUSTRY_PAPER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.DemoAndPosterImpl <em>Demo And Poster</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.DemoAndPosterImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getDemoAndPoster()
   * @generated
   */
  int DEMO_AND_POSTER = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEMO_AND_POSTER__NAME = 0;

  /**
   * The number of structural features of the '<em>Demo And Poster</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEMO_AND_POSTER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.PanelImpl <em>Panel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.PanelImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getPanel()
   * @generated
   */
  int PANEL = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANEL__NAME = 0;

  /**
   * The number of structural features of the '<em>Panel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.LocationImpl <em>Location</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.LocationImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getLocation()
   * @generated
   */
  int LOCATION = 13;

  /**
   * The feature id for the '<em><b>Room</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCATION__ROOM = 0;

  /**
   * The number of structural features of the '<em>Location</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.RoomImpl <em>Room</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.RoomImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getRoom()
   * @generated
   */
  int ROOM = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__NAME = 0;

  /**
   * The number of structural features of the '<em>Room</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.KeynoteImpl <em>Keynote</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.KeynoteImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getKeynote()
   * @generated
   */
  int KEYNOTE = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KEYNOTE__NAME = 0;

  /**
   * The number of structural features of the '<em>Keynote</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KEYNOTE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.CoffeBreakImpl <em>Coffe Break</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.CoffeBreakImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getCoffeBreak()
   * @generated
   */
  int COFFE_BREAK = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COFFE_BREAK__NAME = 0;

  /**
   * The number of structural features of the '<em>Coffe Break</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COFFE_BREAK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.LunchImpl <em>Lunch</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.LunchImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getLunch()
   * @generated
   */
  int LUNCH = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LUNCH__NAME = 0;

  /**
   * The number of structural features of the '<em>Lunch</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LUNCH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.SocialEventImpl <em>Social Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.SocialEventImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getSocialEvent()
   * @generated
   */
  int SOCIAL_EVENT = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOCIAL_EVENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Location</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOCIAL_EVENT__LOCATION = 1;

  /**
   * The feature id for the '<em><b>Start Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOCIAL_EVENT__START_TIME = 2;

  /**
   * The feature id for the '<em><b>End Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOCIAL_EVENT__END_TIME = 3;

  /**
   * The feature id for the '<em><b>Directions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOCIAL_EVENT__DIRECTIONS = 4;

  /**
   * The number of structural features of the '<em>Social Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOCIAL_EVENT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.GoogleMapsDirectionsImpl <em>Google Maps Directions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.conferenceProgram.impl.GoogleMapsDirectionsImpl
   * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getGoogleMapsDirections()
   * @generated
   */
  int GOOGLE_MAPS_DIRECTIONS = 19;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOOGLE_MAPS_DIRECTIONS__URL = 0;

  /**
   * The number of structural features of the '<em>Google Maps Directions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOOGLE_MAPS_DIRECTIONS_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.ConferenceProgram <em>Conference Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conference Program</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgram
   * @generated
   */
  EClass getConferenceProgram();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getName()
   * @see #getConferenceProgram()
   * @generated
   */
  EAttribute getConferenceProgram_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getDate()
   * @see #getConferenceProgram()
   * @generated
   */
  EAttribute getConferenceProgram_Date();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getResearchtracks <em>Researchtracks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Researchtracks</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getResearchtracks()
   * @see #getConferenceProgram()
   * @generated
   */
  EReference getConferenceProgram_Researchtracks();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getIndustrytracks <em>Industrytracks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Industrytracks</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getIndustrytracks()
   * @see #getConferenceProgram()
   * @generated
   */
  EReference getConferenceProgram_Industrytracks();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getDemosandposterstrack <em>Demosandposterstrack</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Demosandposterstrack</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getDemosandposterstrack()
   * @see #getConferenceProgram()
   * @generated
   */
  EReference getConferenceProgram_Demosandposterstrack();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getPanelstrack <em>Panelstrack</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Panelstrack</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getPanelstrack()
   * @see #getConferenceProgram()
   * @generated
   */
  EReference getConferenceProgram_Panelstrack();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getSocialEvents <em>Social Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Social Events</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getSocialEvents()
   * @see #getConferenceProgram()
   * @generated
   */
  EReference getConferenceProgram_SocialEvents();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getKeynotes <em>Keynotes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Keynotes</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getKeynotes()
   * @see #getConferenceProgram()
   * @generated
   */
  EReference getConferenceProgram_Keynotes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getCoffebreaks <em>Coffebreaks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Coffebreaks</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getCoffebreaks()
   * @see #getConferenceProgram()
   * @generated
   */
  EReference getConferenceProgram_Coffebreaks();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getLunches <em>Lunches</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lunches</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgram#getLunches()
   * @see #getConferenceProgram()
   * @generated
   */
  EReference getConferenceProgram_Lunches();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.ResearchTrack <em>Research Track</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Research Track</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ResearchTrack
   * @generated
   */
  EClass getResearchTrack();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.ResearchTrack#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ResearchTrack#getName()
   * @see #getResearchTrack()
   * @generated
   */
  EAttribute getResearchTrack_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.ResearchTrack#getResearchsession <em>Researchsession</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Researchsession</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ResearchTrack#getResearchsession()
   * @see #getResearchTrack()
   * @generated
   */
  EReference getResearchTrack_Researchsession();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.IndustryTrack <em>Industry Track</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Industry Track</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.IndustryTrack
   * @generated
   */
  EClass getIndustryTrack();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.IndustryTrack#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.IndustryTrack#getName()
   * @see #getIndustryTrack()
   * @generated
   */
  EAttribute getIndustryTrack_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.IndustryTrack#getIndutrysession <em>Indutrysession</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Indutrysession</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.IndustryTrack#getIndutrysession()
   * @see #getIndustryTrack()
   * @generated
   */
  EReference getIndustryTrack_Indutrysession();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.DemosAndPosterTrack <em>Demos And Poster Track</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Demos And Poster Track</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.DemosAndPosterTrack
   * @generated
   */
  EClass getDemosAndPosterTrack();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.DemosAndPosterTrack#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.DemosAndPosterTrack#getName()
   * @see #getDemosAndPosterTrack()
   * @generated
   */
  EAttribute getDemosAndPosterTrack_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.DemosAndPosterTrack#getDemosession <em>Demosession</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Demosession</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.DemosAndPosterTrack#getDemosession()
   * @see #getDemosAndPosterTrack()
   * @generated
   */
  EReference getDemosAndPosterTrack_Demosession();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.PanelTrack <em>Panel Track</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Panel Track</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.PanelTrack
   * @generated
   */
  EClass getPanelTrack();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.PanelTrack#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.PanelTrack#getName()
   * @see #getPanelTrack()
   * @generated
   */
  EAttribute getPanelTrack_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.PanelTrack#getPanelsession <em>Panelsession</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Panelsession</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.PanelTrack#getPanelsession()
   * @see #getPanelTrack()
   * @generated
   */
  EReference getPanelTrack_Panelsession();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.ResearchSession <em>Research Session</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Research Session</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ResearchSession
   * @generated
   */
  EClass getResearchSession();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.ResearchSession#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ResearchSession#getName()
   * @see #getResearchSession()
   * @generated
   */
  EAttribute getResearchSession_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.ResearchSession#getResearchpaper <em>Researchpaper</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Researchpaper</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ResearchSession#getResearchpaper()
   * @see #getResearchSession()
   * @generated
   */
  EReference getResearchSession_Researchpaper();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.conferenceProgram.ResearchSession#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Location</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ResearchSession#getLocation()
   * @see #getResearchSession()
   * @generated
   */
  EReference getResearchSession_Location();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.ResearchSession#getStartTime <em>Start Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Time</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ResearchSession#getStartTime()
   * @see #getResearchSession()
   * @generated
   */
  EAttribute getResearchSession_StartTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.ResearchSession#getEndTime <em>End Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Time</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ResearchSession#getEndTime()
   * @see #getResearchSession()
   * @generated
   */
  EAttribute getResearchSession_EndTime();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.IndustrySession <em>Industry Session</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Industry Session</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.IndustrySession
   * @generated
   */
  EClass getIndustrySession();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.IndustrySession#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.IndustrySession#getName()
   * @see #getIndustrySession()
   * @generated
   */
  EAttribute getIndustrySession_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.IndustrySession#getIndustrypaper <em>Industrypaper</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Industrypaper</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.IndustrySession#getIndustrypaper()
   * @see #getIndustrySession()
   * @generated
   */
  EReference getIndustrySession_Industrypaper();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.conferenceProgram.IndustrySession#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Location</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.IndustrySession#getLocation()
   * @see #getIndustrySession()
   * @generated
   */
  EReference getIndustrySession_Location();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.IndustrySession#getStartTime <em>Start Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Time</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.IndustrySession#getStartTime()
   * @see #getIndustrySession()
   * @generated
   */
  EAttribute getIndustrySession_StartTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.IndustrySession#getEndTime <em>End Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Time</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.IndustrySession#getEndTime()
   * @see #getIndustrySession()
   * @generated
   */
  EAttribute getIndustrySession_EndTime();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.DemoSession <em>Demo Session</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Demo Session</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.DemoSession
   * @generated
   */
  EClass getDemoSession();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.DemoSession#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.DemoSession#getName()
   * @see #getDemoSession()
   * @generated
   */
  EAttribute getDemoSession_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.DemoSession#getDemoandposter <em>Demoandposter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Demoandposter</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.DemoSession#getDemoandposter()
   * @see #getDemoSession()
   * @generated
   */
  EReference getDemoSession_Demoandposter();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.conferenceProgram.DemoSession#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Location</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.DemoSession#getLocation()
   * @see #getDemoSession()
   * @generated
   */
  EReference getDemoSession_Location();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.DemoSession#getStartTime <em>Start Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Time</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.DemoSession#getStartTime()
   * @see #getDemoSession()
   * @generated
   */
  EAttribute getDemoSession_StartTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.DemoSession#getEndTime <em>End Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Time</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.DemoSession#getEndTime()
   * @see #getDemoSession()
   * @generated
   */
  EAttribute getDemoSession_EndTime();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.PanelSession <em>Panel Session</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Panel Session</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.PanelSession
   * @generated
   */
  EClass getPanelSession();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.PanelSession#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.PanelSession#getName()
   * @see #getPanelSession()
   * @generated
   */
  EAttribute getPanelSession_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.conferenceProgram.PanelSession#getPanel <em>Panel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Panel</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.PanelSession#getPanel()
   * @see #getPanelSession()
   * @generated
   */
  EReference getPanelSession_Panel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.conferenceProgram.PanelSession#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Location</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.PanelSession#getLocation()
   * @see #getPanelSession()
   * @generated
   */
  EReference getPanelSession_Location();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.PanelSession#getStartTime <em>Start Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Time</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.PanelSession#getStartTime()
   * @see #getPanelSession()
   * @generated
   */
  EAttribute getPanelSession_StartTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.PanelSession#getEndTime <em>End Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Time</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.PanelSession#getEndTime()
   * @see #getPanelSession()
   * @generated
   */
  EAttribute getPanelSession_EndTime();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.ResearchPaper <em>Research Paper</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Research Paper</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ResearchPaper
   * @generated
   */
  EClass getResearchPaper();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.ResearchPaper#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.ResearchPaper#getName()
   * @see #getResearchPaper()
   * @generated
   */
  EAttribute getResearchPaper_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.IndustryPaper <em>Industry Paper</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Industry Paper</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.IndustryPaper
   * @generated
   */
  EClass getIndustryPaper();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.IndustryPaper#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.IndustryPaper#getName()
   * @see #getIndustryPaper()
   * @generated
   */
  EAttribute getIndustryPaper_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.DemoAndPoster <em>Demo And Poster</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Demo And Poster</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.DemoAndPoster
   * @generated
   */
  EClass getDemoAndPoster();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.DemoAndPoster#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.DemoAndPoster#getName()
   * @see #getDemoAndPoster()
   * @generated
   */
  EAttribute getDemoAndPoster_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.Panel <em>Panel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Panel</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.Panel
   * @generated
   */
  EClass getPanel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.Panel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.Panel#getName()
   * @see #getPanel()
   * @generated
   */
  EAttribute getPanel_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.Location <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Location</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.Location
   * @generated
   */
  EClass getLocation();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.conferenceProgram.Location#getRoom <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Room</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.Location#getRoom()
   * @see #getLocation()
   * @generated
   */
  EReference getLocation_Room();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.Room <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.Room
   * @generated
   */
  EClass getRoom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.Room#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.Room#getName()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.Keynote <em>Keynote</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Keynote</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.Keynote
   * @generated
   */
  EClass getKeynote();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.Keynote#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.Keynote#getName()
   * @see #getKeynote()
   * @generated
   */
  EAttribute getKeynote_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.CoffeBreak <em>Coffe Break</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Coffe Break</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.CoffeBreak
   * @generated
   */
  EClass getCoffeBreak();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.CoffeBreak#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.CoffeBreak#getName()
   * @see #getCoffeBreak()
   * @generated
   */
  EAttribute getCoffeBreak_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.Lunch <em>Lunch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lunch</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.Lunch
   * @generated
   */
  EClass getLunch();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.Lunch#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.Lunch#getName()
   * @see #getLunch()
   * @generated
   */
  EAttribute getLunch_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.SocialEvent <em>Social Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Social Event</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.SocialEvent
   * @generated
   */
  EClass getSocialEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.SocialEvent#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.SocialEvent#getName()
   * @see #getSocialEvent()
   * @generated
   */
  EAttribute getSocialEvent_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.conferenceProgram.SocialEvent#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Location</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.SocialEvent#getLocation()
   * @see #getSocialEvent()
   * @generated
   */
  EReference getSocialEvent_Location();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.SocialEvent#getStartTime <em>Start Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start Time</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.SocialEvent#getStartTime()
   * @see #getSocialEvent()
   * @generated
   */
  EAttribute getSocialEvent_StartTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.SocialEvent#getEndTime <em>End Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Time</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.SocialEvent#getEndTime()
   * @see #getSocialEvent()
   * @generated
   */
  EAttribute getSocialEvent_EndTime();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.conferenceProgram.SocialEvent#getDirections <em>Directions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Directions</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.SocialEvent#getDirections()
   * @see #getSocialEvent()
   * @generated
   */
  EReference getSocialEvent_Directions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.conferenceProgram.GoogleMapsDirections <em>Google Maps Directions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Google Maps Directions</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.GoogleMapsDirections
   * @generated
   */
  EClass getGoogleMapsDirections();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.conferenceProgram.GoogleMapsDirections#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.example.mydsl.conferenceProgram.GoogleMapsDirections#getUrl()
   * @see #getGoogleMapsDirections()
   * @generated
   */
  EAttribute getGoogleMapsDirections_Url();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ConferenceProgramFactory getConferenceProgramFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramImpl <em>Conference Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getConferenceProgram()
     * @generated
     */
    EClass CONFERENCE_PROGRAM = eINSTANCE.getConferenceProgram();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFERENCE_PROGRAM__NAME = eINSTANCE.getConferenceProgram_Name();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFERENCE_PROGRAM__DATE = eINSTANCE.getConferenceProgram_Date();

    /**
     * The meta object literal for the '<em><b>Researchtracks</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFERENCE_PROGRAM__RESEARCHTRACKS = eINSTANCE.getConferenceProgram_Researchtracks();

    /**
     * The meta object literal for the '<em><b>Industrytracks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFERENCE_PROGRAM__INDUSTRYTRACKS = eINSTANCE.getConferenceProgram_Industrytracks();

    /**
     * The meta object literal for the '<em><b>Demosandposterstrack</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFERENCE_PROGRAM__DEMOSANDPOSTERSTRACK = eINSTANCE.getConferenceProgram_Demosandposterstrack();

    /**
     * The meta object literal for the '<em><b>Panelstrack</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFERENCE_PROGRAM__PANELSTRACK = eINSTANCE.getConferenceProgram_Panelstrack();

    /**
     * The meta object literal for the '<em><b>Social Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFERENCE_PROGRAM__SOCIAL_EVENTS = eINSTANCE.getConferenceProgram_SocialEvents();

    /**
     * The meta object literal for the '<em><b>Keynotes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFERENCE_PROGRAM__KEYNOTES = eINSTANCE.getConferenceProgram_Keynotes();

    /**
     * The meta object literal for the '<em><b>Coffebreaks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFERENCE_PROGRAM__COFFEBREAKS = eINSTANCE.getConferenceProgram_Coffebreaks();

    /**
     * The meta object literal for the '<em><b>Lunches</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFERENCE_PROGRAM__LUNCHES = eINSTANCE.getConferenceProgram_Lunches();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.ResearchTrackImpl <em>Research Track</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ResearchTrackImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getResearchTrack()
     * @generated
     */
    EClass RESEARCH_TRACK = eINSTANCE.getResearchTrack();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESEARCH_TRACK__NAME = eINSTANCE.getResearchTrack_Name();

    /**
     * The meta object literal for the '<em><b>Researchsession</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESEARCH_TRACK__RESEARCHSESSION = eINSTANCE.getResearchTrack_Researchsession();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.IndustryTrackImpl <em>Industry Track</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.IndustryTrackImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getIndustryTrack()
     * @generated
     */
    EClass INDUSTRY_TRACK = eINSTANCE.getIndustryTrack();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INDUSTRY_TRACK__NAME = eINSTANCE.getIndustryTrack_Name();

    /**
     * The meta object literal for the '<em><b>Indutrysession</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INDUSTRY_TRACK__INDUTRYSESSION = eINSTANCE.getIndustryTrack_Indutrysession();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.DemosAndPosterTrackImpl <em>Demos And Poster Track</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.DemosAndPosterTrackImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getDemosAndPosterTrack()
     * @generated
     */
    EClass DEMOS_AND_POSTER_TRACK = eINSTANCE.getDemosAndPosterTrack();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEMOS_AND_POSTER_TRACK__NAME = eINSTANCE.getDemosAndPosterTrack_Name();

    /**
     * The meta object literal for the '<em><b>Demosession</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEMOS_AND_POSTER_TRACK__DEMOSESSION = eINSTANCE.getDemosAndPosterTrack_Demosession();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.PanelTrackImpl <em>Panel Track</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.PanelTrackImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getPanelTrack()
     * @generated
     */
    EClass PANEL_TRACK = eINSTANCE.getPanelTrack();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PANEL_TRACK__NAME = eINSTANCE.getPanelTrack_Name();

    /**
     * The meta object literal for the '<em><b>Panelsession</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PANEL_TRACK__PANELSESSION = eINSTANCE.getPanelTrack_Panelsession();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.ResearchSessionImpl <em>Research Session</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ResearchSessionImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getResearchSession()
     * @generated
     */
    EClass RESEARCH_SESSION = eINSTANCE.getResearchSession();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESEARCH_SESSION__NAME = eINSTANCE.getResearchSession_Name();

    /**
     * The meta object literal for the '<em><b>Researchpaper</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESEARCH_SESSION__RESEARCHPAPER = eINSTANCE.getResearchSession_Researchpaper();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESEARCH_SESSION__LOCATION = eINSTANCE.getResearchSession_Location();

    /**
     * The meta object literal for the '<em><b>Start Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESEARCH_SESSION__START_TIME = eINSTANCE.getResearchSession_StartTime();

    /**
     * The meta object literal for the '<em><b>End Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESEARCH_SESSION__END_TIME = eINSTANCE.getResearchSession_EndTime();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.IndustrySessionImpl <em>Industry Session</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.IndustrySessionImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getIndustrySession()
     * @generated
     */
    EClass INDUSTRY_SESSION = eINSTANCE.getIndustrySession();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INDUSTRY_SESSION__NAME = eINSTANCE.getIndustrySession_Name();

    /**
     * The meta object literal for the '<em><b>Industrypaper</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INDUSTRY_SESSION__INDUSTRYPAPER = eINSTANCE.getIndustrySession_Industrypaper();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INDUSTRY_SESSION__LOCATION = eINSTANCE.getIndustrySession_Location();

    /**
     * The meta object literal for the '<em><b>Start Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INDUSTRY_SESSION__START_TIME = eINSTANCE.getIndustrySession_StartTime();

    /**
     * The meta object literal for the '<em><b>End Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INDUSTRY_SESSION__END_TIME = eINSTANCE.getIndustrySession_EndTime();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.DemoSessionImpl <em>Demo Session</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.DemoSessionImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getDemoSession()
     * @generated
     */
    EClass DEMO_SESSION = eINSTANCE.getDemoSession();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEMO_SESSION__NAME = eINSTANCE.getDemoSession_Name();

    /**
     * The meta object literal for the '<em><b>Demoandposter</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEMO_SESSION__DEMOANDPOSTER = eINSTANCE.getDemoSession_Demoandposter();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEMO_SESSION__LOCATION = eINSTANCE.getDemoSession_Location();

    /**
     * The meta object literal for the '<em><b>Start Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEMO_SESSION__START_TIME = eINSTANCE.getDemoSession_StartTime();

    /**
     * The meta object literal for the '<em><b>End Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEMO_SESSION__END_TIME = eINSTANCE.getDemoSession_EndTime();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.PanelSessionImpl <em>Panel Session</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.PanelSessionImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getPanelSession()
     * @generated
     */
    EClass PANEL_SESSION = eINSTANCE.getPanelSession();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PANEL_SESSION__NAME = eINSTANCE.getPanelSession_Name();

    /**
     * The meta object literal for the '<em><b>Panel</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PANEL_SESSION__PANEL = eINSTANCE.getPanelSession_Panel();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PANEL_SESSION__LOCATION = eINSTANCE.getPanelSession_Location();

    /**
     * The meta object literal for the '<em><b>Start Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PANEL_SESSION__START_TIME = eINSTANCE.getPanelSession_StartTime();

    /**
     * The meta object literal for the '<em><b>End Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PANEL_SESSION__END_TIME = eINSTANCE.getPanelSession_EndTime();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.ResearchPaperImpl <em>Research Paper</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ResearchPaperImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getResearchPaper()
     * @generated
     */
    EClass RESEARCH_PAPER = eINSTANCE.getResearchPaper();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESEARCH_PAPER__NAME = eINSTANCE.getResearchPaper_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.IndustryPaperImpl <em>Industry Paper</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.IndustryPaperImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getIndustryPaper()
     * @generated
     */
    EClass INDUSTRY_PAPER = eINSTANCE.getIndustryPaper();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INDUSTRY_PAPER__NAME = eINSTANCE.getIndustryPaper_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.DemoAndPosterImpl <em>Demo And Poster</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.DemoAndPosterImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getDemoAndPoster()
     * @generated
     */
    EClass DEMO_AND_POSTER = eINSTANCE.getDemoAndPoster();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEMO_AND_POSTER__NAME = eINSTANCE.getDemoAndPoster_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.PanelImpl <em>Panel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.PanelImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getPanel()
     * @generated
     */
    EClass PANEL = eINSTANCE.getPanel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PANEL__NAME = eINSTANCE.getPanel_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.LocationImpl <em>Location</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.LocationImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getLocation()
     * @generated
     */
    EClass LOCATION = eINSTANCE.getLocation();

    /**
     * The meta object literal for the '<em><b>Room</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOCATION__ROOM = eINSTANCE.getLocation_Room();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.RoomImpl <em>Room</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.RoomImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getRoom()
     * @generated
     */
    EClass ROOM = eINSTANCE.getRoom();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__NAME = eINSTANCE.getRoom_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.KeynoteImpl <em>Keynote</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.KeynoteImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getKeynote()
     * @generated
     */
    EClass KEYNOTE = eINSTANCE.getKeynote();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute KEYNOTE__NAME = eINSTANCE.getKeynote_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.CoffeBreakImpl <em>Coffe Break</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.CoffeBreakImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getCoffeBreak()
     * @generated
     */
    EClass COFFE_BREAK = eINSTANCE.getCoffeBreak();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COFFE_BREAK__NAME = eINSTANCE.getCoffeBreak_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.LunchImpl <em>Lunch</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.LunchImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getLunch()
     * @generated
     */
    EClass LUNCH = eINSTANCE.getLunch();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LUNCH__NAME = eINSTANCE.getLunch_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.SocialEventImpl <em>Social Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.SocialEventImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getSocialEvent()
     * @generated
     */
    EClass SOCIAL_EVENT = eINSTANCE.getSocialEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOCIAL_EVENT__NAME = eINSTANCE.getSocialEvent_Name();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SOCIAL_EVENT__LOCATION = eINSTANCE.getSocialEvent_Location();

    /**
     * The meta object literal for the '<em><b>Start Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOCIAL_EVENT__START_TIME = eINSTANCE.getSocialEvent_StartTime();

    /**
     * The meta object literal for the '<em><b>End Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOCIAL_EVENT__END_TIME = eINSTANCE.getSocialEvent_EndTime();

    /**
     * The meta object literal for the '<em><b>Directions</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SOCIAL_EVENT__DIRECTIONS = eINSTANCE.getSocialEvent_Directions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.conferenceProgram.impl.GoogleMapsDirectionsImpl <em>Google Maps Directions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.conferenceProgram.impl.GoogleMapsDirectionsImpl
     * @see org.xtext.example.mydsl.conferenceProgram.impl.ConferenceProgramPackageImpl#getGoogleMapsDirections()
     * @generated
     */
    EClass GOOGLE_MAPS_DIRECTIONS = eINSTANCE.getGoogleMapsDirections();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOOGLE_MAPS_DIRECTIONS__URL = eINSTANCE.getGoogleMapsDirections_Url();

  }

} //ConferenceProgramPackage
