/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.conferenceProgram;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Session</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.conferenceProgram.Session#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.conferenceProgram.Session#getResearchpaper <em>Researchpaper</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.conferenceProgram.Session#getIndustrypaper <em>Industrypaper</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.conferenceProgram.Session#getDemoandposter <em>Demoandposter</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.conferenceProgram.Session#getPanel <em>Panel</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.conferenceProgram.Session#getLocation <em>Location</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.conferenceProgram.Session#getStartTime <em>Start Time</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.conferenceProgram.Session#getEndTime <em>End Time</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgramPackage#getSession()
 * @model
 * @generated
 */
public interface Session extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgramPackage#getSession_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.conferenceProgram.Session#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Researchpaper</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.conferenceProgram.ResearchPaper}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Researchpaper</em>' containment reference list.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgramPackage#getSession_Researchpaper()
   * @model containment="true"
   * @generated
   */
  EList<ResearchPaper> getResearchpaper();

  /**
   * Returns the value of the '<em><b>Industrypaper</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.conferenceProgram.IndustryPaper}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Industrypaper</em>' containment reference list.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgramPackage#getSession_Industrypaper()
   * @model containment="true"
   * @generated
   */
  EList<IndustryPaper> getIndustrypaper();

  /**
   * Returns the value of the '<em><b>Demoandposter</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.conferenceProgram.DemoAndPoster}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Demoandposter</em>' containment reference list.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgramPackage#getSession_Demoandposter()
   * @model containment="true"
   * @generated
   */
  EList<DemoAndPoster> getDemoandposter();

  /**
   * Returns the value of the '<em><b>Panel</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.conferenceProgram.Panel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Panel</em>' containment reference list.
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgramPackage#getSession_Panel()
   * @model containment="true"
   * @generated
   */
  EList<Panel> getPanel();

  /**
   * Returns the value of the '<em><b>Location</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Location</em>' containment reference.
   * @see #setLocation(Location)
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgramPackage#getSession_Location()
   * @model containment="true"
   * @generated
   */
  Location getLocation();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.conferenceProgram.Session#getLocation <em>Location</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Location</em>' containment reference.
   * @see #getLocation()
   * @generated
   */
  void setLocation(Location value);

  /**
   * Returns the value of the '<em><b>Start Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Time</em>' attribute.
   * @see #setStartTime(String)
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgramPackage#getSession_StartTime()
   * @model
   * @generated
   */
  String getStartTime();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.conferenceProgram.Session#getStartTime <em>Start Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Time</em>' attribute.
   * @see #getStartTime()
   * @generated
   */
  void setStartTime(String value);

  /**
   * Returns the value of the '<em><b>End Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Time</em>' attribute.
   * @see #setEndTime(String)
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgramPackage#getSession_EndTime()
   * @model
   * @generated
   */
  String getEndTime();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.conferenceProgram.Session#getEndTime <em>End Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Time</em>' attribute.
   * @see #getEndTime()
   * @generated
   */
  void setEndTime(String value);

} // Session
