/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.conferenceProgram.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.mydsl.conferenceProgram.CoffeBreak;
import org.xtext.example.mydsl.conferenceProgram.ConferenceProgram;
import org.xtext.example.mydsl.conferenceProgram.ConferenceProgramFactory;
import org.xtext.example.mydsl.conferenceProgram.ConferenceProgramPackage;
import org.xtext.example.mydsl.conferenceProgram.DemoAndPoster;
import org.xtext.example.mydsl.conferenceProgram.DemoSession;
import org.xtext.example.mydsl.conferenceProgram.DemosAndPosterTrack;
import org.xtext.example.mydsl.conferenceProgram.GoogleMapsDirections;
import org.xtext.example.mydsl.conferenceProgram.IndustryPaper;
import org.xtext.example.mydsl.conferenceProgram.IndustrySession;
import org.xtext.example.mydsl.conferenceProgram.IndustryTrack;
import org.xtext.example.mydsl.conferenceProgram.Keynote;
import org.xtext.example.mydsl.conferenceProgram.Location;
import org.xtext.example.mydsl.conferenceProgram.Lunch;
import org.xtext.example.mydsl.conferenceProgram.Panel;
import org.xtext.example.mydsl.conferenceProgram.PanelSession;
import org.xtext.example.mydsl.conferenceProgram.PanelTrack;
import org.xtext.example.mydsl.conferenceProgram.ResearchPaper;
import org.xtext.example.mydsl.conferenceProgram.ResearchSession;
import org.xtext.example.mydsl.conferenceProgram.ResearchTrack;
import org.xtext.example.mydsl.conferenceProgram.Room;
import org.xtext.example.mydsl.conferenceProgram.SocialEvent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ConferenceProgramPackageImpl extends EPackageImpl implements ConferenceProgramPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass conferenceProgramEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass researchTrackEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass industryTrackEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass demosAndPosterTrackEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass panelTrackEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass researchSessionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass industrySessionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass demoSessionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass panelSessionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass researchPaperEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass industryPaperEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass demoAndPosterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass panelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass locationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass roomEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass keynoteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass coffeBreakEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lunchEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass socialEventEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass googleMapsDirectionsEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.mydsl.conferenceProgram.ConferenceProgramPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private ConferenceProgramPackageImpl()
  {
    super(eNS_URI, ConferenceProgramFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link ConferenceProgramPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static ConferenceProgramPackage init()
  {
    if (isInited) return (ConferenceProgramPackage)EPackage.Registry.INSTANCE.getEPackage(ConferenceProgramPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredConferenceProgramPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    ConferenceProgramPackageImpl theConferenceProgramPackage = registeredConferenceProgramPackage instanceof ConferenceProgramPackageImpl ? (ConferenceProgramPackageImpl)registeredConferenceProgramPackage : new ConferenceProgramPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theConferenceProgramPackage.createPackageContents();

    // Initialize created meta-data
    theConferenceProgramPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theConferenceProgramPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(ConferenceProgramPackage.eNS_URI, theConferenceProgramPackage);
    return theConferenceProgramPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConferenceProgram()
  {
    return conferenceProgramEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getConferenceProgram_Name()
  {
    return (EAttribute)conferenceProgramEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getConferenceProgram_Date()
  {
    return (EAttribute)conferenceProgramEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getConferenceProgram_Researchtracks()
  {
    return (EReference)conferenceProgramEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getConferenceProgram_Industrytracks()
  {
    return (EReference)conferenceProgramEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getConferenceProgram_Demosandposterstrack()
  {
    return (EReference)conferenceProgramEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getConferenceProgram_Panelstrack()
  {
    return (EReference)conferenceProgramEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getConferenceProgram_SocialEvents()
  {
    return (EReference)conferenceProgramEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getConferenceProgram_Keynotes()
  {
    return (EReference)conferenceProgramEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getConferenceProgram_Coffebreaks()
  {
    return (EReference)conferenceProgramEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getConferenceProgram_Lunches()
  {
    return (EReference)conferenceProgramEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getResearchTrack()
  {
    return researchTrackEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getResearchTrack_Name()
  {
    return (EAttribute)researchTrackEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getResearchTrack_Researchsession()
  {
    return (EReference)researchTrackEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIndustryTrack()
  {
    return industryTrackEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIndustryTrack_Name()
  {
    return (EAttribute)industryTrackEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIndustryTrack_Indutrysession()
  {
    return (EReference)industryTrackEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDemosAndPosterTrack()
  {
    return demosAndPosterTrackEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDemosAndPosterTrack_Name()
  {
    return (EAttribute)demosAndPosterTrackEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDemosAndPosterTrack_Demosession()
  {
    return (EReference)demosAndPosterTrackEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPanelTrack()
  {
    return panelTrackEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPanelTrack_Name()
  {
    return (EAttribute)panelTrackEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPanelTrack_Panelsession()
  {
    return (EReference)panelTrackEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getResearchSession()
  {
    return researchSessionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getResearchSession_Name()
  {
    return (EAttribute)researchSessionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getResearchSession_Researchpaper()
  {
    return (EReference)researchSessionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getResearchSession_Location()
  {
    return (EReference)researchSessionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getResearchSession_StartTime()
  {
    return (EAttribute)researchSessionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getResearchSession_EndTime()
  {
    return (EAttribute)researchSessionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIndustrySession()
  {
    return industrySessionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIndustrySession_Name()
  {
    return (EAttribute)industrySessionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIndustrySession_Industrypaper()
  {
    return (EReference)industrySessionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIndustrySession_Location()
  {
    return (EReference)industrySessionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIndustrySession_StartTime()
  {
    return (EAttribute)industrySessionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIndustrySession_EndTime()
  {
    return (EAttribute)industrySessionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDemoSession()
  {
    return demoSessionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDemoSession_Name()
  {
    return (EAttribute)demoSessionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDemoSession_Demoandposter()
  {
    return (EReference)demoSessionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDemoSession_Location()
  {
    return (EReference)demoSessionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDemoSession_StartTime()
  {
    return (EAttribute)demoSessionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDemoSession_EndTime()
  {
    return (EAttribute)demoSessionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPanelSession()
  {
    return panelSessionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPanelSession_Name()
  {
    return (EAttribute)panelSessionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPanelSession_Panel()
  {
    return (EReference)panelSessionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPanelSession_Location()
  {
    return (EReference)panelSessionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPanelSession_StartTime()
  {
    return (EAttribute)panelSessionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPanelSession_EndTime()
  {
    return (EAttribute)panelSessionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getResearchPaper()
  {
    return researchPaperEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getResearchPaper_Name()
  {
    return (EAttribute)researchPaperEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIndustryPaper()
  {
    return industryPaperEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIndustryPaper_Name()
  {
    return (EAttribute)industryPaperEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDemoAndPoster()
  {
    return demoAndPosterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDemoAndPoster_Name()
  {
    return (EAttribute)demoAndPosterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPanel()
  {
    return panelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPanel_Name()
  {
    return (EAttribute)panelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLocation()
  {
    return locationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLocation_Room()
  {
    return (EReference)locationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRoom()
  {
    return roomEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRoom_Name()
  {
    return (EAttribute)roomEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getKeynote()
  {
    return keynoteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getKeynote_Name()
  {
    return (EAttribute)keynoteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCoffeBreak()
  {
    return coffeBreakEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCoffeBreak_Name()
  {
    return (EAttribute)coffeBreakEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLunch()
  {
    return lunchEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLunch_Name()
  {
    return (EAttribute)lunchEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSocialEvent()
  {
    return socialEventEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSocialEvent_Name()
  {
    return (EAttribute)socialEventEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSocialEvent_Location()
  {
    return (EReference)socialEventEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSocialEvent_StartTime()
  {
    return (EAttribute)socialEventEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSocialEvent_EndTime()
  {
    return (EAttribute)socialEventEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSocialEvent_Directions()
  {
    return (EReference)socialEventEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGoogleMapsDirections()
  {
    return googleMapsDirectionsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGoogleMapsDirections_Url()
  {
    return (EAttribute)googleMapsDirectionsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConferenceProgramFactory getConferenceProgramFactory()
  {
    return (ConferenceProgramFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    conferenceProgramEClass = createEClass(CONFERENCE_PROGRAM);
    createEAttribute(conferenceProgramEClass, CONFERENCE_PROGRAM__NAME);
    createEAttribute(conferenceProgramEClass, CONFERENCE_PROGRAM__DATE);
    createEReference(conferenceProgramEClass, CONFERENCE_PROGRAM__RESEARCHTRACKS);
    createEReference(conferenceProgramEClass, CONFERENCE_PROGRAM__INDUSTRYTRACKS);
    createEReference(conferenceProgramEClass, CONFERENCE_PROGRAM__DEMOSANDPOSTERSTRACK);
    createEReference(conferenceProgramEClass, CONFERENCE_PROGRAM__PANELSTRACK);
    createEReference(conferenceProgramEClass, CONFERENCE_PROGRAM__SOCIAL_EVENTS);
    createEReference(conferenceProgramEClass, CONFERENCE_PROGRAM__KEYNOTES);
    createEReference(conferenceProgramEClass, CONFERENCE_PROGRAM__COFFEBREAKS);
    createEReference(conferenceProgramEClass, CONFERENCE_PROGRAM__LUNCHES);

    researchTrackEClass = createEClass(RESEARCH_TRACK);
    createEAttribute(researchTrackEClass, RESEARCH_TRACK__NAME);
    createEReference(researchTrackEClass, RESEARCH_TRACK__RESEARCHSESSION);

    industryTrackEClass = createEClass(INDUSTRY_TRACK);
    createEAttribute(industryTrackEClass, INDUSTRY_TRACK__NAME);
    createEReference(industryTrackEClass, INDUSTRY_TRACK__INDUTRYSESSION);

    demosAndPosterTrackEClass = createEClass(DEMOS_AND_POSTER_TRACK);
    createEAttribute(demosAndPosterTrackEClass, DEMOS_AND_POSTER_TRACK__NAME);
    createEReference(demosAndPosterTrackEClass, DEMOS_AND_POSTER_TRACK__DEMOSESSION);

    panelTrackEClass = createEClass(PANEL_TRACK);
    createEAttribute(panelTrackEClass, PANEL_TRACK__NAME);
    createEReference(panelTrackEClass, PANEL_TRACK__PANELSESSION);

    researchSessionEClass = createEClass(RESEARCH_SESSION);
    createEAttribute(researchSessionEClass, RESEARCH_SESSION__NAME);
    createEReference(researchSessionEClass, RESEARCH_SESSION__RESEARCHPAPER);
    createEReference(researchSessionEClass, RESEARCH_SESSION__LOCATION);
    createEAttribute(researchSessionEClass, RESEARCH_SESSION__START_TIME);
    createEAttribute(researchSessionEClass, RESEARCH_SESSION__END_TIME);

    industrySessionEClass = createEClass(INDUSTRY_SESSION);
    createEAttribute(industrySessionEClass, INDUSTRY_SESSION__NAME);
    createEReference(industrySessionEClass, INDUSTRY_SESSION__INDUSTRYPAPER);
    createEReference(industrySessionEClass, INDUSTRY_SESSION__LOCATION);
    createEAttribute(industrySessionEClass, INDUSTRY_SESSION__START_TIME);
    createEAttribute(industrySessionEClass, INDUSTRY_SESSION__END_TIME);

    demoSessionEClass = createEClass(DEMO_SESSION);
    createEAttribute(demoSessionEClass, DEMO_SESSION__NAME);
    createEReference(demoSessionEClass, DEMO_SESSION__DEMOANDPOSTER);
    createEReference(demoSessionEClass, DEMO_SESSION__LOCATION);
    createEAttribute(demoSessionEClass, DEMO_SESSION__START_TIME);
    createEAttribute(demoSessionEClass, DEMO_SESSION__END_TIME);

    panelSessionEClass = createEClass(PANEL_SESSION);
    createEAttribute(panelSessionEClass, PANEL_SESSION__NAME);
    createEReference(panelSessionEClass, PANEL_SESSION__PANEL);
    createEReference(panelSessionEClass, PANEL_SESSION__LOCATION);
    createEAttribute(panelSessionEClass, PANEL_SESSION__START_TIME);
    createEAttribute(panelSessionEClass, PANEL_SESSION__END_TIME);

    researchPaperEClass = createEClass(RESEARCH_PAPER);
    createEAttribute(researchPaperEClass, RESEARCH_PAPER__NAME);

    industryPaperEClass = createEClass(INDUSTRY_PAPER);
    createEAttribute(industryPaperEClass, INDUSTRY_PAPER__NAME);

    demoAndPosterEClass = createEClass(DEMO_AND_POSTER);
    createEAttribute(demoAndPosterEClass, DEMO_AND_POSTER__NAME);

    panelEClass = createEClass(PANEL);
    createEAttribute(panelEClass, PANEL__NAME);

    locationEClass = createEClass(LOCATION);
    createEReference(locationEClass, LOCATION__ROOM);

    roomEClass = createEClass(ROOM);
    createEAttribute(roomEClass, ROOM__NAME);

    keynoteEClass = createEClass(KEYNOTE);
    createEAttribute(keynoteEClass, KEYNOTE__NAME);

    coffeBreakEClass = createEClass(COFFE_BREAK);
    createEAttribute(coffeBreakEClass, COFFE_BREAK__NAME);

    lunchEClass = createEClass(LUNCH);
    createEAttribute(lunchEClass, LUNCH__NAME);

    socialEventEClass = createEClass(SOCIAL_EVENT);
    createEAttribute(socialEventEClass, SOCIAL_EVENT__NAME);
    createEReference(socialEventEClass, SOCIAL_EVENT__LOCATION);
    createEAttribute(socialEventEClass, SOCIAL_EVENT__START_TIME);
    createEAttribute(socialEventEClass, SOCIAL_EVENT__END_TIME);
    createEReference(socialEventEClass, SOCIAL_EVENT__DIRECTIONS);

    googleMapsDirectionsEClass = createEClass(GOOGLE_MAPS_DIRECTIONS);
    createEAttribute(googleMapsDirectionsEClass, GOOGLE_MAPS_DIRECTIONS__URL);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(conferenceProgramEClass, ConferenceProgram.class, "ConferenceProgram", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConferenceProgram_Name(), ecorePackage.getEString(), "name", null, 0, 1, ConferenceProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getConferenceProgram_Date(), ecorePackage.getEString(), "date", null, 0, 1, ConferenceProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConferenceProgram_Researchtracks(), this.getResearchTrack(), null, "researchtracks", null, 0, 1, ConferenceProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConferenceProgram_Industrytracks(), this.getIndustryTrack(), null, "industrytracks", null, 0, -1, ConferenceProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConferenceProgram_Demosandposterstrack(), this.getDemosAndPosterTrack(), null, "demosandposterstrack", null, 0, -1, ConferenceProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConferenceProgram_Panelstrack(), this.getPanelTrack(), null, "panelstrack", null, 0, -1, ConferenceProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConferenceProgram_SocialEvents(), this.getSocialEvent(), null, "socialEvents", null, 0, -1, ConferenceProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConferenceProgram_Keynotes(), this.getKeynote(), null, "keynotes", null, 0, -1, ConferenceProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConferenceProgram_Coffebreaks(), this.getCoffeBreak(), null, "coffebreaks", null, 0, -1, ConferenceProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConferenceProgram_Lunches(), this.getLunch(), null, "lunches", null, 0, -1, ConferenceProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(researchTrackEClass, ResearchTrack.class, "ResearchTrack", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getResearchTrack_Name(), ecorePackage.getEString(), "name", null, 0, 1, ResearchTrack.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getResearchTrack_Researchsession(), this.getResearchSession(), null, "researchsession", null, 0, -1, ResearchTrack.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(industryTrackEClass, IndustryTrack.class, "IndustryTrack", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIndustryTrack_Name(), ecorePackage.getEString(), "name", null, 0, 1, IndustryTrack.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getIndustryTrack_Indutrysession(), this.getIndustrySession(), null, "indutrysession", null, 0, -1, IndustryTrack.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(demosAndPosterTrackEClass, DemosAndPosterTrack.class, "DemosAndPosterTrack", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDemosAndPosterTrack_Name(), ecorePackage.getEString(), "name", null, 0, 1, DemosAndPosterTrack.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDemosAndPosterTrack_Demosession(), this.getDemoSession(), null, "demosession", null, 0, -1, DemosAndPosterTrack.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(panelTrackEClass, PanelTrack.class, "PanelTrack", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPanelTrack_Name(), ecorePackage.getEString(), "name", null, 0, 1, PanelTrack.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPanelTrack_Panelsession(), this.getPanelSession(), null, "panelsession", null, 0, -1, PanelTrack.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(researchSessionEClass, ResearchSession.class, "ResearchSession", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getResearchSession_Name(), ecorePackage.getEString(), "name", null, 0, 1, ResearchSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getResearchSession_Researchpaper(), this.getResearchPaper(), null, "researchpaper", null, 0, -1, ResearchSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getResearchSession_Location(), this.getLocation(), null, "location", null, 0, 1, ResearchSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getResearchSession_StartTime(), ecorePackage.getEString(), "startTime", null, 0, 1, ResearchSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getResearchSession_EndTime(), ecorePackage.getEString(), "endTime", null, 0, 1, ResearchSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(industrySessionEClass, IndustrySession.class, "IndustrySession", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIndustrySession_Name(), ecorePackage.getEString(), "name", null, 0, 1, IndustrySession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getIndustrySession_Industrypaper(), this.getIndustryPaper(), null, "industrypaper", null, 0, -1, IndustrySession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getIndustrySession_Location(), this.getLocation(), null, "location", null, 0, 1, IndustrySession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getIndustrySession_StartTime(), ecorePackage.getEString(), "startTime", null, 0, 1, IndustrySession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getIndustrySession_EndTime(), ecorePackage.getEString(), "endTime", null, 0, 1, IndustrySession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(demoSessionEClass, DemoSession.class, "DemoSession", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDemoSession_Name(), ecorePackage.getEString(), "name", null, 0, 1, DemoSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDemoSession_Demoandposter(), this.getDemoAndPoster(), null, "demoandposter", null, 0, -1, DemoSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDemoSession_Location(), this.getLocation(), null, "location", null, 0, 1, DemoSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDemoSession_StartTime(), ecorePackage.getEString(), "startTime", null, 0, 1, DemoSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDemoSession_EndTime(), ecorePackage.getEString(), "endTime", null, 0, 1, DemoSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(panelSessionEClass, PanelSession.class, "PanelSession", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPanelSession_Name(), ecorePackage.getEString(), "name", null, 0, 1, PanelSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPanelSession_Panel(), this.getPanel(), null, "panel", null, 0, -1, PanelSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPanelSession_Location(), this.getLocation(), null, "location", null, 0, 1, PanelSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPanelSession_StartTime(), ecorePackage.getEString(), "startTime", null, 0, 1, PanelSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPanelSession_EndTime(), ecorePackage.getEString(), "endTime", null, 0, 1, PanelSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(researchPaperEClass, ResearchPaper.class, "ResearchPaper", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getResearchPaper_Name(), ecorePackage.getEString(), "name", null, 0, 1, ResearchPaper.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(industryPaperEClass, IndustryPaper.class, "IndustryPaper", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIndustryPaper_Name(), ecorePackage.getEString(), "name", null, 0, 1, IndustryPaper.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(demoAndPosterEClass, DemoAndPoster.class, "DemoAndPoster", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDemoAndPoster_Name(), ecorePackage.getEString(), "name", null, 0, 1, DemoAndPoster.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(panelEClass, Panel.class, "Panel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPanel_Name(), ecorePackage.getEString(), "name", null, 0, 1, Panel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(locationEClass, Location.class, "Location", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLocation_Room(), this.getRoom(), null, "room", null, 0, 1, Location.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(roomEClass, Room.class, "Room", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRoom_Name(), ecorePackage.getEString(), "name", null, 0, 1, Room.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(keynoteEClass, Keynote.class, "Keynote", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getKeynote_Name(), ecorePackage.getEString(), "name", null, 0, 1, Keynote.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(coffeBreakEClass, CoffeBreak.class, "CoffeBreak", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCoffeBreak_Name(), ecorePackage.getEString(), "name", null, 0, 1, CoffeBreak.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lunchEClass, Lunch.class, "Lunch", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLunch_Name(), ecorePackage.getEString(), "name", null, 0, 1, Lunch.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(socialEventEClass, SocialEvent.class, "SocialEvent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSocialEvent_Name(), ecorePackage.getEString(), "name", null, 0, 1, SocialEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSocialEvent_Location(), this.getLocation(), null, "location", null, 0, 1, SocialEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSocialEvent_StartTime(), ecorePackage.getEString(), "startTime", null, 0, 1, SocialEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSocialEvent_EndTime(), ecorePackage.getEString(), "endTime", null, 0, 1, SocialEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSocialEvent_Directions(), this.getGoogleMapsDirections(), null, "directions", null, 0, 1, SocialEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(googleMapsDirectionsEClass, GoogleMapsDirections.class, "GoogleMapsDirections", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGoogleMapsDirections_Url(), ecorePackage.getEString(), "url", null, 0, 1, GoogleMapsDirections.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //ConferenceProgramPackageImpl
