/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.conferenceProgram.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.conferenceProgram.ConferenceProgramPackage;
import org.xtext.example.mydsl.conferenceProgram.GoogleMapsDirections;
import org.xtext.example.mydsl.conferenceProgram.Location;
import org.xtext.example.mydsl.conferenceProgram.SocialEvent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Social Event</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.conferenceProgram.impl.SocialEventImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.conferenceProgram.impl.SocialEventImpl#getLocation <em>Location</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.conferenceProgram.impl.SocialEventImpl#getStartTime <em>Start Time</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.conferenceProgram.impl.SocialEventImpl#getEndTime <em>End Time</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.conferenceProgram.impl.SocialEventImpl#getDirections <em>Directions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SocialEventImpl extends MinimalEObjectImpl.Container implements SocialEvent
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getLocation() <em>Location</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocation()
   * @generated
   * @ordered
   */
  protected Location location;

  /**
   * The default value of the '{@link #getStartTime() <em>Start Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartTime()
   * @generated
   * @ordered
   */
  protected static final String START_TIME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStartTime() <em>Start Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStartTime()
   * @generated
   * @ordered
   */
  protected String startTime = START_TIME_EDEFAULT;

  /**
   * The default value of the '{@link #getEndTime() <em>End Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEndTime()
   * @generated
   * @ordered
   */
  protected static final String END_TIME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEndTime() <em>End Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEndTime()
   * @generated
   * @ordered
   */
  protected String endTime = END_TIME_EDEFAULT;

  /**
   * The cached value of the '{@link #getDirections() <em>Directions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirections()
   * @generated
   * @ordered
   */
  protected GoogleMapsDirections directions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SocialEventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ConferenceProgramPackage.Literals.SOCIAL_EVENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ConferenceProgramPackage.SOCIAL_EVENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Location getLocation()
  {
    return location;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLocation(Location newLocation, NotificationChain msgs)
  {
    Location oldLocation = location;
    location = newLocation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ConferenceProgramPackage.SOCIAL_EVENT__LOCATION, oldLocation, newLocation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLocation(Location newLocation)
  {
    if (newLocation != location)
    {
      NotificationChain msgs = null;
      if (location != null)
        msgs = ((InternalEObject)location).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ConferenceProgramPackage.SOCIAL_EVENT__LOCATION, null, msgs);
      if (newLocation != null)
        msgs = ((InternalEObject)newLocation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ConferenceProgramPackage.SOCIAL_EVENT__LOCATION, null, msgs);
      msgs = basicSetLocation(newLocation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ConferenceProgramPackage.SOCIAL_EVENT__LOCATION, newLocation, newLocation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getStartTime()
  {
    return startTime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStartTime(String newStartTime)
  {
    String oldStartTime = startTime;
    startTime = newStartTime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ConferenceProgramPackage.SOCIAL_EVENT__START_TIME, oldStartTime, startTime));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEndTime()
  {
    return endTime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEndTime(String newEndTime)
  {
    String oldEndTime = endTime;
    endTime = newEndTime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ConferenceProgramPackage.SOCIAL_EVENT__END_TIME, oldEndTime, endTime));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GoogleMapsDirections getDirections()
  {
    return directions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDirections(GoogleMapsDirections newDirections, NotificationChain msgs)
  {
    GoogleMapsDirections oldDirections = directions;
    directions = newDirections;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ConferenceProgramPackage.SOCIAL_EVENT__DIRECTIONS, oldDirections, newDirections);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDirections(GoogleMapsDirections newDirections)
  {
    if (newDirections != directions)
    {
      NotificationChain msgs = null;
      if (directions != null)
        msgs = ((InternalEObject)directions).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ConferenceProgramPackage.SOCIAL_EVENT__DIRECTIONS, null, msgs);
      if (newDirections != null)
        msgs = ((InternalEObject)newDirections).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ConferenceProgramPackage.SOCIAL_EVENT__DIRECTIONS, null, msgs);
      msgs = basicSetDirections(newDirections, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ConferenceProgramPackage.SOCIAL_EVENT__DIRECTIONS, newDirections, newDirections));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ConferenceProgramPackage.SOCIAL_EVENT__LOCATION:
        return basicSetLocation(null, msgs);
      case ConferenceProgramPackage.SOCIAL_EVENT__DIRECTIONS:
        return basicSetDirections(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ConferenceProgramPackage.SOCIAL_EVENT__NAME:
        return getName();
      case ConferenceProgramPackage.SOCIAL_EVENT__LOCATION:
        return getLocation();
      case ConferenceProgramPackage.SOCIAL_EVENT__START_TIME:
        return getStartTime();
      case ConferenceProgramPackage.SOCIAL_EVENT__END_TIME:
        return getEndTime();
      case ConferenceProgramPackage.SOCIAL_EVENT__DIRECTIONS:
        return getDirections();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ConferenceProgramPackage.SOCIAL_EVENT__NAME:
        setName((String)newValue);
        return;
      case ConferenceProgramPackage.SOCIAL_EVENT__LOCATION:
        setLocation((Location)newValue);
        return;
      case ConferenceProgramPackage.SOCIAL_EVENT__START_TIME:
        setStartTime((String)newValue);
        return;
      case ConferenceProgramPackage.SOCIAL_EVENT__END_TIME:
        setEndTime((String)newValue);
        return;
      case ConferenceProgramPackage.SOCIAL_EVENT__DIRECTIONS:
        setDirections((GoogleMapsDirections)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ConferenceProgramPackage.SOCIAL_EVENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ConferenceProgramPackage.SOCIAL_EVENT__LOCATION:
        setLocation((Location)null);
        return;
      case ConferenceProgramPackage.SOCIAL_EVENT__START_TIME:
        setStartTime(START_TIME_EDEFAULT);
        return;
      case ConferenceProgramPackage.SOCIAL_EVENT__END_TIME:
        setEndTime(END_TIME_EDEFAULT);
        return;
      case ConferenceProgramPackage.SOCIAL_EVENT__DIRECTIONS:
        setDirections((GoogleMapsDirections)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ConferenceProgramPackage.SOCIAL_EVENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ConferenceProgramPackage.SOCIAL_EVENT__LOCATION:
        return location != null;
      case ConferenceProgramPackage.SOCIAL_EVENT__START_TIME:
        return START_TIME_EDEFAULT == null ? startTime != null : !START_TIME_EDEFAULT.equals(startTime);
      case ConferenceProgramPackage.SOCIAL_EVENT__END_TIME:
        return END_TIME_EDEFAULT == null ? endTime != null : !END_TIME_EDEFAULT.equals(endTime);
      case ConferenceProgramPackage.SOCIAL_EVENT__DIRECTIONS:
        return directions != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", startTime: ");
    result.append(startTime);
    result.append(", endTime: ");
    result.append(endTime);
    result.append(')');
    return result.toString();
  }

} //SocialEventImpl
