/*
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.conferenceProgram.ui.internal.ConferenceProgramActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConferenceProgramExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ConferenceProgramActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ConferenceProgramActivator activator = ConferenceProgramActivator.getInstance();
		return activator != null ? activator.getInjector(ConferenceProgramActivator.ORG_XTEXT_EXAMPLE_MYDSL_CONFERENCEPROGRAM) : null;
	}

}
