/*
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.conferenceProgram.ui.internal.ConferenceProgramActivator;

public class ConferenceProgramUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ConferenceProgramActivator.getInstance().getInjector("org.xtext.example.mydsl.ConferenceProgram");
	}

}
