/*
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalConferenceProgramParser;
import org.xtext.example.mydsl.services.ConferenceProgramGrammarAccess;

public class ConferenceProgramParser extends AbstractAntlrParser {

	@Inject
	private ConferenceProgramGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalConferenceProgramParser createParser(XtextTokenStream stream) {
		return new InternalConferenceProgramParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ConferenceProgram";
	}

	public ConferenceProgramGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ConferenceProgramGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
