/*
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.ConferenceProgramRuntimeModule;
import org.xtext.example.mydsl.ConferenceProgramStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ConferenceProgramIdeSetup extends ConferenceProgramStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ConferenceProgramRuntimeModule(), new ConferenceProgramIdeModule()));
	}
	
}
